//
// Created by yekai on 2021/12/29.
//

#ifndef PICO_LINK_IO_CONFIG_H
#define PICO_LINK_IO_CONFIG_H

#define LED_PIN 4
#define LED_STATE_ON true
#define LED_STATE_OFF false

#define PICO_LINK_SWCLK 27
#define PICO_LINK_SWDIO 26
#define PICO_LINK_RESET 22

#define PICO_LINK_SWCLK_MASK (1ul << PICO_LINK_SWCLK)
#define PICO_LINK_SWDIO_MASK (1ul << PICO_LINK_SWDIO)
#define PICO_LINK_RESET_MASK (1ul << PICO_LINK_RESET)

#define PICO_LINK_UART_TX 20
#define PICO_LINK_UART_RX 21
#define PICO_LINK_UART_ID uart1
#define PICO_LINK_UART_IRQ UART1_IRQ

#endif //PICO_LINK_IO_CONFIG_H
