//
// Created by yekai on 2021/12/29.
//

#ifndef PICO_LINK_IO_CONFIG_H
#define PICO_LINK_IO_CONFIG_H

#define LED_PIN PICO_DEFAULT_LED_PIN

#define PICO_LINK_SWCLK 11
#define PICO_LINK_SWDIO_OUT 9
#define PICO_LINK_SWDIO_IN 10
#define PICO_LINK_RESET 17

#define PICO_LINK_SWCLK_MASK (1ul << PICO_LINK_SWCLK)
#define PICO_LINK_SWDIO_OUT_MASK (1ul << PICO_LINK_SWDIO_OUT)
#define PICO_LINK_SWDIO_IN_MASK (1ul << PICO_LINK_SWDIO_IN)
#define PICO_LINK_RESET_MASK (1ul << PICO_LINK_RESET)

#define PICO_LINK_UART_TX 12
#define PICO_LINK_UART_RX 13
#define PICO_LINK_UART_ID uart1
#define PICO_LINK_UART_IRQ UART1_IRQ

#endif //PICO_LINK_IO_CONFIG_H
